apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-1
  namespace: demo
  labels:
    app: app-server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server-1
  template:
    metadata:
      labels:
        app: app-server-1
    spec:
      containers:
      - name: app-container
        image: toluid/java
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: demo
  labels:
    app: app-server-1
spec:
  selector:
    app: app-server-1
  type: ClusterIP  
  ports:
  - port: 80
    targetPort: 8080