apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-2
  namespace: demo
  labels:
    app: app-server-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-server-2
  template:
    metadata:
      labels:
        app: app-server-2
    spec:
      containers:
      - name: app2-container
        image: toluid/vulnssl
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: demo
  labels:
    app: app-server-2
spec:
  selector:
    app: app-server-2
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080